
        public class gajikaryawan extends javax.swing.JFrame {

            /**
             * Creates new form gajikaryawan
             */
            public gajikaryawan() {
                initComponents();
            }
        
            /**
             * This method is called from within the constructor to initialize the form.
             * WARNING: Do NOT modify this code. The content of this method is always
             * regenerated by the Form Editor.
             */
            @SuppressWarnings("unchecked")
            // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
            private void initComponents() {
        
                jLabel1 = new javax.swing.JLabel();
                jLabel2 = new javax.swing.JLabel();
                jLabel3 = new javax.swing.JLabel();
                jLabel4 = new javax.swing.JLabel();
                jLabel5 = new javax.swing.JLabel();
                jLabel6 = new javax.swing.JLabel();
                jLabel7 = new javax.swing.JLabel();
                jLabel8 = new javax.swing.JLabel();
                jLabel9 = new javax.swing.JLabel();
                txtnik = new javax.swing.JTextField();
                txtnm = new javax.swing.JTextField();
                txtgaji = new javax.swing.JTextField();
                txtlbr = new javax.swing.JTextField();
                cmblbr = new javax.swing.JComboBox<>();
                cmbjk = new javax.swing.JComboBox<>();
                cmbjb = new javax.swing.JComboBox<>();
                txttg = new javax.swing.JTextField();
                btnhitung = new javax.swing.JButton();
                btnout = new javax.swing.JButton();
        
                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        
                jLabel1.setText("Penggajian Karyawan");
        
                jLabel2.setText("NIK");
        
                jLabel3.setText("Nama Karyawan");
        
                jLabel4.setText("Jenis Kelamin");
        
                jLabel5.setText("Jabatan");
        
                jLabel6.setText("Gaji Pokok");
        
                jLabel7.setText("Jam Lembur");
        
                jLabel8.setText("Upah Lembur");
        
                jLabel9.setText("Total Gaji");
        
                txtnik.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        txtnikActionPerformed(evt);
                    }
                });
        
                txtnm.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        txtnmActionPerformed(evt);
                    }
                });
        
                cmblbr.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " --Pilih Jam Lembur--", "1 Jam", "2 Jam", "3 Jam", "4 Jam", "5 Jam" }));
                cmblbr.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        cmblbrActionPerformed(evt);
                    }
                });
        
                cmbjk.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " --Pilih Jenis Kelamin--", "Laki-laki", "Perempuan" }));
        
                cmbjb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " --Pilih Jabatan--", "Manajer", "Personalia", "Customer Service", "Security" }));
                cmbjb.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        cmbjbActionPerformed(evt);
                    }
                });
        
                txttg.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        txttgActionPerformed(evt);
                    }
                });
        
                btnhitung.setText("Hitung");
                btnhitung.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        btnhitungActionPerformed(evt);
                    }
                });
        
                btnout.setText("Batal");
                btnout.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        btnoutActionPerformed(evt);
                    }
                });
        
                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtnik)
                            .addComponent(cmbjb, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbjk, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtnm))
                        .addGap(104, 104, 104)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtlbr, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmblbr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtgaji, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 35, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(280, 280, 280)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txttg, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(21, 21, 21)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnhitung)
                        .addGap(111, 111, 111)
                        .addComponent(btnout)
                        .addGap(208, 208, 208))
                );
                layout.setVerticalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1)
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6)
                            .addComponent(txtnik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtgaji, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7)
                            .addComponent(txtnm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmblbr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel8)
                            .addComponent(txtlbr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbjk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(cmbjb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addComponent(jLabel9)
                        .addGap(11, 11, 11)
                        .addComponent(txttg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnhitung)
                            .addComponent(btnout))
                        .addGap(36, 36, 36))
                );
        
                pack();
            }// </editor-fold>                        
        
            private void txtnmActionPerformed(java.awt.event.ActionEvent evt) {                                      
                // TODO add your handling code here:
            }                                     
        
            private void txttgActionPerformed(java.awt.event.ActionEvent evt) {                                      
                // TODO add your handling code here:
            }                                     
        
            private void txtnikActionPerformed(java.awt.event.ActionEvent evt) {                                       
                // TODO add your handling code here:
            }                                      
        
            private void cmbjbActionPerformed(java.awt.event.ActionEvent evt) {                                      
        if (cmbjb.getSelectedItem().equals("--Pilih Jabatan--")){
                     txtgaji.setText("");
                }
                 else if (cmbjb.getSelectedItem().equals("Manajer")){
                     txtgaji.setText("3000000");
                }
                 else if (cmbjb.getSelectedItem().equals("Personalia")){
                     txtgaji.setText("2500000");
                }
                 else if (cmbjb.getSelectedItem().equals("Customer Service")){
                     txtgaji.setText("2000000");
                }
                 else if (cmbjb.getSelectedItem().equals("Security")){
                     txtgaji.setText("1700000");
                }        
            }                                     
        
            private void cmblbrActionPerformed(java.awt.event.ActionEvent evt) {                                       
             if (cmblbr.getSelectedItem().equals("--Pilih Jam Lembur--")){
                     txtlbr.setText("");
                }
                 else if (cmblbr.getSelectedItem().equals("1 Jam")){
                     txtlbr.setText("50000");
                }
                 else if (cmblbr.getSelectedItem().equals("2 Jam")){
                     txtlbr.setText("100000");
                }
                 else if (cmblbr.getSelectedItem().equals("3 Jam")){
                     txtlbr.setText("150000");
                }
                  else if (cmblbr.getSelectedItem().equals("4 Jam")){
                     txtlbr.setText("200000");
                }
                  else if (cmblbr.getSelectedItem().equals("5 Jam")){
                     txtlbr.setText("250000");
                }
            }                                      
        
            private void btnhitungActionPerformed(java.awt.event.ActionEvent evt) {                                          
            int x=Integer.parseInt(txtgaji.getText());
         int y=Integer.parseInt(txtlbr.getText());
         int total=x+y;
         txttg.setText(String.valueOf(total));
            }                                         
        
            private void btnoutActionPerformed(java.awt.event.ActionEvent evt) {                                       
            txtnik.setText (null); 
           txtnm.setText (null);
           txtgaji.setText (null);
           txtlbr.setText (null);
           txttg.setText (null);
            }                                      
        
            /**
             * @param args the command line arguments
             */
            public static void main(String args[]) {
                /* Set the Nimbus look and feel */
                //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
                /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
                 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
                 */
                try {
                    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                        if ("Nimbus".equals(info.getName())) {
                            javax.swing.UIManager.setLookAndFeel(info.getClassName());
                            break;
                        }
                    }
                } catch (ClassNotFoundException ex) {
                    java.util.logging.Logger.getLogger(gajikaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                    java.util.logging.Logger.getLogger(gajikaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                    java.util.logging.Logger.getLogger(gajikaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                    java.util.logging.Logger.getLogger(gajikaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                }
                //</editor-fold>
        
                /* Create and display the form */
                java.awt.EventQueue.invokeLater(new Runnable() {
                    public void run() {
                        new gajikaryawan().setVisible(true);
                    }
                });
            }
        
            // Variables declaration - do not modify                     
            private javax.swing.JButton btnhitung;
            private javax.swing.JButton btnout;
            private javax.swing.JComboBox<String> cmbjb;
            private javax.swing.JComboBox<String> cmbjk;
            private javax.swing.JComboBox<String> cmblbr;
            private javax.swing.JLabel jLabel1;
            private javax.swing.JLabel jLabel2;
            private javax.swing.JLabel jLabel3;
            private javax.swing.JLabel jLabel4;
            private javax.swing.JLabel jLabel5;
            private javax.swing.JLabel jLabel6;
            private javax.swing.JLabel jLabel7;
            private javax.swing.JLabel jLabel8;
            private javax.swing.JLabel jLabel9;
            private javax.swing.JTextField txtgaji;
            private javax.swing.JTextField txtlbr;
            private javax.swing.JTextField txtnik;
            private javax.swing.JTextField txtnm;
            private javax.swing.JTextField txttg;
            // End of variables declaration                   
         }

